// dllmain.cpp - GRW-XR proxy entry point.
//
// PHASE 1 SCOPE, deliberately small:
//   load, prove we are inside GRW.exe, log identity, forward every dxgi export.
//   No hooks. No D3D. No OpenXR. Nothing that can crash the game.
//
// The point of phase 1 is to answer docs/QUESTIONS.md Q1 with evidence rather
// than inference: does a dxgi.dll placed beside GRW.exe actually get loaded?
// If grwxr.log appears, the answer is yes and the whole architecture is sound.
// If it does not, we learn that now instead of after building on the assumption.
//
// Two things this deliberately does NOT copy from the reference implementation
// (see docs/REFERENCE-ANALYSIS.md A1 and A6):
//   1. Its DllMain switch is missing a `break` and falls through from
//      DLL_PROCESS_ATTACH. Ours does not.
//   2. Its init thread does a bare Sleep(5000) and hopes the engine is ready.
//      Ours waits on an actual condition with a bounded timeout, so it is both
//      faster when the engine is quick and safer when it is slow.
//
// Loader-lock discipline: DllMain does the absolute minimum and immediately
// hands off to a worker thread. No file I/O, no LoadLibrary, no CRT init work
// happens inside DllMain itself.

#define WIN32_LEAN_AND_MEAN
#define NOMINMAX
#include <windows.h>

#include "Log.h"
#include "D3D11Hook.h"
#include "GameBuild.h"
#include "Crash.h"
#include "VRMirror.h"
#include "AnselProbe.h"
#include "CameraProbe.h"
#include "FactoryHook.h"
#include "XInputMerge.h"
#include "RenderDocCapture.h"
#include "PaletteProbe.h"
#include "WeaponDraw.h"
#include "WeaponProbe.h"
#include "AimTrace.h"
#include "Voice.h"
#include "Menu.h"
#include "Presets.h"

// Forward every export of the real dxgi.dll to dxgi_real.dll.
// deploy.bat places a copy of C:\Windows\System32\dxgi.dll as dxgi_real.dll
// beside the game executable. Generated by tools/gen_proxy_exports.py.
#include "proxy_exports.inc"

namespace {

HMODULE g_self = nullptr;

// Is this the process we are meant to be in? A proxy DLL sitting in a game
// directory can be picked up by launchers, overlays and helper processes. We
// only want to do work inside the game itself.
bool host_is_target() {
    wchar_t exe[MAX_PATH] = {};
    GetModuleFileNameW(nullptr, exe, MAX_PATH);
    std::wstring s = exe;
    for (auto& c : s) c = (wchar_t)towlower(c);
    return s.find(L"grw.exe") != std::wstring::npos;
}

// Wait until the graphics stack is actually present, instead of sleeping a
// fixed five seconds and hoping. Returns true if d3d11 showed up.
bool wait_for_graphics(DWORD timeout_ms) {
    const DWORD step = 50;
    DWORD waited = 0;
    while (waited < timeout_ms) {
        if (GetModuleHandleW(L"d3d11.dll") != nullptr) return true;
        Sleep(step);
        waited += step;
    }
    return false;
}

DWORD WINAPI init_thread(LPVOID) {
    grwxr::log::init(g_self);
    grwxr::crash::install(g_self);

    LOG_INFO("GRW-XR proxy attached. Phase 1: load and log only, no hooks installed.");

    if (!host_is_target()) {
        LOG_WARN("host is not GRW.exe. Standing down, forwarding only.");
        return 0;
    }
    LOG_INFO("host confirmed as GRW.exe");

    // Record which dxgi we are forwarding to, so a mis-deploy is obvious.
    if (HMODULE real = GetModuleHandleW(L"dxgi_real.dll")) {
        wchar_t p[MAX_PATH] = {};
        GetModuleFileNameW(real, p, MAX_PATH);
        char n[MAX_PATH] = {};
        WideCharToMultiByte(CP_UTF8, 0, p, -1, n, sizeof(n), nullptr, nullptr);
        LOG_INFO("forwarding to  : %s", n);
    } else {
        // Not loaded YET is normal, because forwarded exports resolve lazily.
        // Not PRESENT ON DISK is fatal and silent: every export of this proxy
        // forwards to dxgi_real.<name>, so the first DXGI call the game makes
        // dies inside the loader with no exception we can catch, moments after
        // this thread has finished logging a healthy-looking startup.
        //
        // That is exactly how it presented in a tester's report (2026-08-06):
        // all 11 hooks attached cleanly, the log simply stopped, and the game
        // crashed "right after setup". He had extracted the zip into the game
        // folder without running install.bat, which is the only thing that
        // creates dxgi_real.dll. The old wording here called it normal and
        // sent him hunting Ubisoft overlays and anti-cheat for hours.
        wchar_t self_path[MAX_PATH] = {};
        GetModuleFileNameW(g_self, self_path, MAX_PATH);
        std::wstring realpath = self_path;
        const size_t cut = realpath.find_last_of(L'\\');
        realpath = (cut == std::wstring::npos)
                       ? std::wstring(L"dxgi_real.dll")
                       : realpath.substr(0, cut + 1) + L"dxgi_real.dll";
        if (GetFileAttributesW(realpath.c_str()) == INVALID_FILE_ATTRIBUTES) {
            char n[MAX_PATH * 2] = {};
            WideCharToMultiByte(CP_UTF8, 0, realpath.c_str(), -1, n,
                                (int)sizeof(n), nullptr, nullptr);
            LOG_ERROR("");
            LOG_ERROR("################ FATAL: dxgi_real.dll IS MISSING ################");
            LOG_ERROR("  expected at: %s", n);
            LOG_ERROR("  Every export of this proxy forwards to that file. The");
            LOG_ERROR("  game WILL crash the moment it makes its first graphics");
            LOG_ERROR("  call, which is usually seconds from now, and the crash");
            LOG_ERROR("  happens inside Windows' loader so nothing else is logged.");
            LOG_ERROR("  FIX: run install.bat from the release zip. It copies your");
            LOG_ERROR("  own C:\\Windows\\System32\\dxgi.dll to dxgi_real.dll.");
            LOG_ERROR("  Copying the mod files in by hand is NOT enough on its own.");
            LOG_ERROR("  If the game is under Program Files, run it as administrator");
            LOG_ERROR("  or the copy will be refused.");
            LOG_ERROR("################################################################");
            LOG_ERROR("");
        } else {
            LOG_INFO("dxgi_real.dll present on disk, not yet loaded (normal: "
                     "forwarded exports resolve lazily)");
        }
    }

    // Build 26: RENDERDOC CAPTURE MODE, cfg-gated, off by default.
    //
    // This must happen HERE, before anything else touches graphics, because
    // renderdoc.dll has to be loaded before the game creates its D3D11 device
    // in order to hook it. RenderDoc's own injection cannot reach this process
    // at all (Uplay broker + Secure Boot; see docs/RENDERDOC-GUIDE.md 3b), so
    // loading it from inside is the only route left.
    //
    // When it is on, the VR path STANDS DOWN completely: no factory spoof, no
    // Present hook, no OpenXR, no probes. RenderDoc and our proxy would
    // otherwise both be hooking the same swapchain, which is exactly the
    // situation that produces empty or misleading captures. The mod becomes a
    // dxgi forwarder plus a capture key, nothing more.
    if (grwxr::rdoc::enabled()) {
        LOG_INFO("");
        LOG_INFO("=== RENDERDOC CAPTURE MODE (renderdoc_capture=1 in grwxr.cfg) ===");
        LOG_INFO("VR is STOOD DOWN: no factory spoof, no Present hook, no OpenXR.");
        LOG_INFO("Set renderdoc_capture=0 and relaunch to get VR back.");
        if (!grwxr::rdoc::install()) {
            LOG_WARN("rdoc: capture mode requested but unavailable. The game runs "
                     "UNMODIFIED (rule 7). Fix the cfg or set renderdoc_capture=0.");
        }
        for (int tick = 0; ; ++tick) {
            Sleep(1000);
            grwxr::rdoc::poll();
            grwxr::rdoc::drain();
        }
    }

    // Build 15a: the factory stubs may already have fired (the game creates
    // its device the moment dxgi is loaded); report their state and the
    // upsize target now, then drain their events with the other modules.
    grwxr::factory::report_startup();

    // Build 15c: the engine sizes its renderer from the window client size,
    // so the client size the game sees must lie before the renderer reads it.
    grwxr::factory::install_render_size_spoof();

    const bool gfx = wait_for_graphics(30000);
    LOG_INFO("d3d11.dll present: %s", gfx ? "yes" : "NO (timed out after 30s)");

    // Log the loaded graphics modules and where they came from. This is the
    // evidence for Q1 and Q7 that we could not get from outside, because the
    // live process is protected and PowerShell reads zero modules from it.
    const wchar_t* interesting[] = {
        L"dxgi.dll", L"dxgi_real.dll", L"d3d11.dll", L"d3d12.dll",
        L"xinput1_3.dll", L"dinput8.dll", L"EasyAntiCheat_x64.dll",
        L"AnselSDK64.dll", L"openxr_loader.dll", L"steam_api64.dll",
        L"uplay_r1_loader64.dll", L"nvapi64.dll",
    };
    LOG_INFO("--- module survey ---");
    for (const wchar_t* m : interesting) {
        HMODULE h = GetModuleHandleW(m);
        if (!h) {
            char n[64] = {};
            WideCharToMultiByte(CP_UTF8, 0, m, -1, n, sizeof(n), nullptr, nullptr);
            LOG_INFO("  %-24s not loaded", n);
            continue;
        }
        wchar_t p[MAX_PATH] = {};
        GetModuleFileNameW(h, p, MAX_PATH);
        char nm[64] = {}, pn[MAX_PATH] = {};
        WideCharToMultiByte(CP_UTF8, 0, m, -1, nm, sizeof(nm), nullptr, nullptr);
        WideCharToMultiByte(CP_UTF8, 0, p, -1, pn, sizeof(pn), nullptr, nullptr);
        LOG_INFO("  %-24s 0x%p  %s", nm, (void*)h, pn);
    }
    LOG_INFO("--- end module survey ---");

    // Build 46: identify the loaded binary and pick its address table
    // (fail-closed; see GameBuild.h). Logged before any consumer installs so
    // a refusal below always has its reason above it in the log.
    LOG_INFO("");
    grwxr::gamebuild::log_identity();

    // --- PHASE 2: capture the game's D3D11 device via a vtable hook ---------
    LOG_INFO("");
    LOG_INFO("phase 4 step 1: hooking ansel::setConfiguration for the basis vectors");
    grwxr::ansel::install();

    // Phase 4 step 2 (Q9). Read-only: it records the projection parameters and
    // calls the engine's own function unchanged. A signature miss logs loudly
    // and installs nothing, so a failure here cannot break the game.
    LOG_INFO("");
    LOG_INFO("phase 4 step 2: installing the read-only projection probe (Q9)");
    grwxr::camera::install();

    // Build 39: read-only observer on the pooled placement SetTransform,
    // hunting the weapon's handle (user scope call: "the gun rides the
    // controller"). A signature or thunk mismatch logs and installs nothing.
    LOG_INFO("");
    LOG_INFO("build 39: installing the weapon placement observer");
    grwxr::wp::install();

    // Build 50: the aim-reader census. LOG-ONLY, and the route to making the
    // SHOT follow the controller: it records which engine code reads the
    // player's absolute aim angle, and which of those reads happen inside a
    // trigger pull. Installed after the setters (CameraProbe) because it uses
    // their latched player-object pointer as its filter.
    LOG_INFO("");
    LOG_INFO("build 50: installing the aim-reader census (log-only)");
    grwxr::aimtrace::install();
    // Build 105: separate call on purpose. install() above returns early on
    // cfg aim_probes=0, and these two hooks must not share that fate.
    grwxr::aimtrace::install_aimpoint();
    // Build 107: spoken test instructions. Its own thread and its own COM
    // apartment, so nothing here can reach the render path (rule 8).
    grwxr::voice::init();

    LOG_INFO("phase 2: installing D3D11 Present hook");
    if (!grwxr::d3d11::install()) {
        LOG_WARN("phase 2 hook NOT installed. Game continues unmodified (rule 7).");
        return 0;
    }
    LOG_INFO("phase 2 hook installed. Waiting for the first Present.");

    // Build 129: take the preset inventory now, so the log names what the
    // digit keys will do BEFORE the first one is pressed. A key whose effect
    // is only discoverable by pressing it is the failure mode Numpad 5 taught.
    grwxr::presets::init();

    // Present deliberately writes no log lines. Drain its findings here, on our
    // own thread, and report liveness periodically without touching the hot path.
    // Heartbeat every second. A 30 second interval told us nothing about WHEN it
    // died; a 1 second heartbeat pins the death to a one second window and tells
    // us the frame count it reached, which distinguishes "died immediately on the
    // first frames" from "ran fine then died at a specific event".
    unsigned long long last = 0;
    for (int tick = 0; ; ++tick) {
        // BUILD 77: the second is spent in 50 ms slices so hotkeys are read at
        // 20 Hz instead of 1 Hz, with the KEY-IS-DOWN bit and our own edge
        // detection.
        //
        // Builds 74 and 76 used GetAsyncKeyState's pressed-since-last-call bit
        // on a once-a-second poll, and neither F1 nor NUMPAD 4 ever registered
        // a single press across a whole session. The reason is that the bit is
        // consumed by whoever calls first, and the game polls input every
        // frame, so it was almost always already cleared by the time we looked.
        // The keys that have always worked in this mod (NUMPAD 7, NUMPAD 8) are
        // read at frame rate off the down bit, which is the pattern this now
        // matches. A tester pressing a key and getting nothing is the exact
        // failure the panel exists to remove, and it is worse when the cause is
        // ours.
        {
            static bool f1_prev = false, np4_prev = false, kend_prev = false;
            static bool ndiv_prev = false, nmul_prev = false, nadd_prev = false;
            static bool kins_prev = false, kpgu_prev = false;
            static bool kpgd_prev = false, kdel_prev = false;
            for (int slice = 0; slice < 20; ++slice) {
                Sleep(50);
                const bool f1 = (GetAsyncKeyState(VK_F1) & 0x8000) != 0;
                if (f1 && !f1_prev && grwxr::menu::ready())
                    grwxr::menu::toggle();
                f1_prev = f1;

                // Build 82: NUMPAD 4 was the wnode_axis cycler. That path is
                // retired (build 80 supersedes it) but the key stayed live and
                // logged cheerfully while doing nothing, which is exactly what
                // made a "nothing happened" report take a log dig to explain.
                // Retire the key with its feature; give it to the question we
                // are actually asking.
                // BUILD 104: RETIRED, for the second time and for a better
                // reason. This key armed the spawn-direction write with NO cfg
                // key of its own: one press bent the value that seeds a round,
                // by up to 20 degrees, with nothing but aim_probes between a
                // stray keypress and a live shot-direction experiment.
                //
                // `[VERIFIED, 2026-08-15]` the object it writes into is a
                // TrailFX, the cosmetic bullet trail, so it cannot move a shot
                // in any case. It is a hotkey that arms a retracted lever, and
                // this build is going to testers. Rule 6: revert failed
                // experiments rather than leaving dormant switches in the tree.
                //
                // cfg bullet_yaw_deg still reaches the same code for research;
                // it just cannot be reached by feel from inside a headset.
                (void)np4_prev;

                // Build 93: NUMPAD 5 IS RETIRED, for the same reason NUMPAD 4
                // was retired in build 82, and rule 6 (revert failed
                // experiments rather than leaving dormant switches).
                //
                // It cycled the gun-root bone through off / node 8 / node 10 /
                // rotate, a build 78 A/B that is long settled: the mount is
                // node 10 and the mode is 3, both headset-verified, and node 8
                // was measured to do nothing at all. Three of the four
                // positions this key could select were retired states, and one
                // of them silently disarms the headline feature of the mod.
                //
                // It did exactly that on 2026-08-15. Five presses landed inside
                // one second at 04:27:19 while the tester was working the keys
                // around it, the cycle stopped on mode 0, and the weapon writer
                // sat disarmed for the rest of the session: `wgun: idle
                // node=-1`, rots frozen at 2164 while calls climbed past
                // 690,000. It presented as "the rotation and control from the
                // front hand is gone" and read as a regression in that day's
                // camera work, which it was not. The only feedback the mod gave
                // was a log line, and the tester was wearing a headset.
                //
                // NUMPAD 5 also sits in the middle of the block he uses
                // constantly: 1 cycles barrel aim, 3 toggles ADS, 4 cycles
                // bullet yaw, 8 toggles first person. cfg `wgun` still selects
                // the mode for anyone who wants the old A/B, and it hot-reloads
                // in about a second, so nothing is actually lost here.

                // BUILD 129 (owner directive, 2026-08-22): THE WHOLE DIGIT ROW
                // LOADS WHOLE CONFIGS. "now we can hot reload whole CFG's and
                // map them to 10 keys via the numpad. We can test over 100
                // configs in a single session now."
                //
                // What the digits used to do, and where each went. Nothing is
                // lost and nothing is left dormant (rule 6): every one of them
                // already had, or now has, a row in the F1 panel, which as of
                // build 128 is driveable from the headset.
                //
                //   1  cycle_aim_barrel      -> Settings row "Bullets follow
                //                               the barrel" (aim_barrel)
                //   3  toggle_aim_ads        -> Settings row "Trigger also
                //                               aims down sights" (aim_ads)
                //   0  toggle_cam_pose       -> Settings row added in this
                //                               build (cam_selector_pose)
                //   7  weapon draw census    -> Captures row, already there
                //   8  first person toggle   -> Captures row, already there.
                //                               Its RECENTER half is not lost:
                //                               Home has always recentered on
                //                               its own (VRMirror.cpp), and
                //                               this build adds Space too.
                //   9  eye sign swap         -> Settings row "Swap the eyes",
                //                               put there by build 125b
                //
                // Why a whole config and not one more setting: build 99's note
                // says one key per setting does not scale, and answered it with
                // a tuner that selects WHICH setting is live. That still moves
                // one value at a time, and "does this feel right" is a
                // judgement about a COMBINATION of values. Ten keys times ten
                // banks is a hundred combinations in one session.
                //
                // The keys only queue (Presets.h): the load happens in pump()
                // below, on this thread, because it is file I/O.
                {
                    static bool np_prev[10] = {};
                    static const int vk[10] = {
                        VK_NUMPAD0, VK_NUMPAD1, VK_NUMPAD2, VK_NUMPAD3,
                        VK_NUMPAD4, VK_NUMPAD5, VK_NUMPAD6, VK_NUMPAD7,
                        VK_NUMPAD8, VK_NUMPAD9};
                    for (int d = 0; d < 10; ++d) {
                        const bool down = (GetAsyncKeyState(vk[d]) & 0x8000) != 0;
                        if (down && !np_prev[d]) grwxr::presets::load_slot(d);
                        np_prev[d] = down;
                    }
                }
                grwxr::presets::pump();

                // Build 97 (user directive): the settings an open test asks him
                // to change are reachable from inside the headset. The
                // arithmetic row and the tall + key, because none of them
                // borders a live digit key. See VRMirror.h.
                const bool ndiv = (GetAsyncKeyState(VK_DIVIDE) & 0x8000) != 0;
                if (ndiv && !ndiv_prev) grwxr::vr::step_ipd_scale(-1);
                ndiv_prev = ndiv;

                const bool nmul = (GetAsyncKeyState(VK_MULTIPLY) & 0x8000) != 0;
                if (nmul && !nmul_prev) grwxr::vr::step_ipd_scale(+1);
                nmul_prev = nmul;

                const bool nadd = (GetAsyncKeyState(VK_ADD) & 0x8000) != 0;
                if (nadd && !nadd_prev) grwxr::vr::toggle_cam_pose_rot();
                nadd_prev = nadd;

                // Build 99: THE TUNER. One key selects, two step, one resets,
                // so no future setting ever needs another key. The six-key
                // island above the arrows: findable by feel, and nowhere near
                // the numpad, so nothing here can be hit while reaching for
                // first person or the barrel aim. See VRMirror.h.
                const bool kins = (GetAsyncKeyState(VK_INSERT) & 0x8000) != 0;
                if (kins && !kins_prev) grwxr::vr::tuner_cycle();
                kins_prev = kins;

                // Build 101: Shift makes a step ten times bigger, because the
                // tester spent thirty-one presses against a rail and should not
                // have had to spend fifteen to reach it either.
                const int tmul =
                    (GetAsyncKeyState(VK_SHIFT) & 0x8000) != 0 ? 10 : 1;

                const bool kpgu = (GetAsyncKeyState(VK_PRIOR) & 0x8000) != 0;
                if (kpgu && !kpgu_prev) grwxr::vr::tuner_step(+1, tmul);
                kpgu_prev = kpgu;

                const bool kpgd = (GetAsyncKeyState(VK_NEXT) & 0x8000) != 0;
                if (kpgd && !kpgd_prev) grwxr::vr::tuner_step(-1, tmul);
                kpgd_prev = kpgd;

                // Build 107: End starts a GUIDED, SPOKEN test run. It is the
                // bottom-middle key of the same six-key island as the tuner,
                // so it is findable by feel, and it is the only key in that
                // island that was still free.
                const bool kend = (GetAsyncKeyState(VK_END) & 0x8000) != 0;
                if (kend && !kend_prev) grwxr::aimtrace::guide_start();
                kend_prev = kend;

                const bool kdel = (GetAsyncKeyState(VK_DELETE) & 0x8000) != 0;
                if (kdel && !kdel_prev) grwxr::vr::tuner_reset();
                kdel_prev = kdel;
            }
        }
        grwxr::d3d11::drain_capture_log();
        grwxr::vr::drain_log();
        grwxr::vr::drain_input();
        grwxr::vr::poll_config();
        // Right after poll_config so a cfg edit lands in the same tick that
        // read it. Init thread: this does COM work and logs, both banned on
        // the render thread (rule 8).
        grwxr::d3d11::poll_max_frame_latency();
        grwxr::xin::poll_install();
        grwxr::xin::drain();
        grwxr::ansel::drain();
        grwxr::camera::drain();
        grwxr::factory::drain();
        grwxr::wp::drain();
        grwxr::aimtrace::drain();
        grwxr::aimtrace::drain_aimpoint();

        // Bring OpenXR up once the device exists, on OUR thread, not the render
        // thread. Session creation is slow and allocates; it must not happen
        // inside Present (project rule 8).
        static bool vr_tried = false, vr_armed = false;
        const auto& st = grwxr::d3d11::state();
        if (!vr_tried && st.ready && st.device) {
            vr_tried = true;
            vr_armed = grwxr::vr::init(st);
        } else if (vr_tried && !vr_armed) {
            // Build 38: the headset was not awake when the game launched. Keep
            // watching; the session begins by itself when it wakes, instead of
            // the old behaviour of failing for the whole run.
            vr_armed = grwxr::vr::poll_start();
        }
        if (vr_armed && !grwxr::d3d11::has_present_callback()) {
            grwxr::d3d11::set_present_callback(&grwxr::vr::on_present);
            LOG_INFO("VR mirror armed: the game frame is now going to the headset.");
        }

        // Build 33: the skinning-palette probe (PaletteProbe.h). Installed
        // once the game's immediate context exists; inert until NUMPAD MINUS
        // arms a capture window. All its logging happens in poll(), here.
        static bool pal_tried = false;
        if (!pal_tried && st.ready && st.context) {
            pal_tried = true;
            grwxr::pal::install(st.device, st.context);
        }
        grwxr::pal::poll();

        // 2026-08-09: the weapon draw census (WeaponDraw.h). Shares the draw
        // detours pal installed; NUMPAD 7 walks it through weapon-visible,
        // weapon-gone, dump. Log only, and inert until that key is pressed.
        grwxr::weapondraw::poll();

        // The tester panel (Menu.h). Built on the game's own device once it
        // exists, exactly as the palette probe is. This build renders NO
        // pixels: it proves that ImGui links, that a context and a font atlas
        // come up on a Denuvo-protected process's D3D11 device, and that the
        // toggle works, before any of it goes near the render thread.
        static bool menu_tried = false;
        if (!menu_tried && st.ready && st.device && st.context) {
            menu_tried = true;
            grwxr::menu::init(st.device, st.context);
        }
        // F1 toggles. GetAsyncKeyState's low bit means "pressed since the last
        // call", so a 1 Hz poll on this thread still catches a quick tap and we
        // do not have to put a key read in Present for it.
        grwxr::menu::poll();

        const unsigned long long now = grwxr::d3d11::frame_count();
        LOG_INFO("hb %4d  frames=%llu  (+%llu in the last second)",
                 tick, now, now - last);
        last = now;
    }
}

}  // namespace

BOOL APIENTRY DllMain(HMODULE module, DWORD reason, LPVOID) {
    switch (reason) {
        case DLL_PROCESS_ATTACH: {
            g_self = module;
            // Cuts thread attach/detach churn; we never use TLS callbacks.
            DisableThreadLibraryCalls(module);
            // Hand off immediately: nothing heavy may run under loader lock.
            if (HANDLE t = CreateThread(nullptr, 0, init_thread, nullptr, 0, nullptr)) {
                CloseHandle(t);
            }
            break;   // the reference implementation is missing this break
        }
        case DLL_PROCESS_DETACH:
            // Distinguishes an orderly shutdown from a hard kill: if this line
            // appears, the process unloaded us properly rather than dying.
            LOG_INFO("DLL_PROCESS_DETACH after %llu frames (orderly unload)",
                     grwxr::d3d11::frame_count());
            grwxr::log::shutdown();
            break;
        default:
            break;
    }
    return TRUE;
}
