// dllmain.cpp - GRW-XR proxy entry point.
//
// PHASE 1 SCOPE, deliberately small:
//   load, prove we are inside GRW.exe, log identity, forward every dxgi export.
//   No hooks. No D3D. No OpenXR. Nothing that can crash the game.
//
// The point of phase 1 is to answer docs/QUESTIONS.md Q1 with evidence rather
// than inference: does a dxgi.dll placed beside GRW.exe actually get loaded?
// If grwxr.log appears, the answer is yes and the whole architecture is sound.
// If it does not, we learn that now instead of after building on the assumption.
//
// Two things this deliberately does NOT copy from the reference implementation
// (see docs/REFERENCE-ANALYSIS.md A1 and A6):
//   1. Its DllMain switch is missing a `break` and falls through from
//      DLL_PROCESS_ATTACH. Ours does not.
//   2. Its init thread does a bare Sleep(5000) and hopes the engine is ready.
//      Ours waits on an actual condition with a bounded timeout, so it is both
//      faster when the engine is quick and safer when it is slow.
//
// Loader-lock discipline: DllMain does the absolute minimum and immediately
// hands off to a worker thread. No file I/O, no LoadLibrary, no CRT init work
// happens inside DllMain itself.

#define WIN32_LEAN_AND_MEAN
#define NOMINMAX
#include <windows.h>

#include "Log.h"
#include "D3D11Hook.h"
#include "GameBuild.h"
#include "Crash.h"
#include "VRMirror.h"
#include "AnselProbe.h"
#include "CameraProbe.h"
#include "FactoryHook.h"
#include "XInputMerge.h"
#include "RenderDocCapture.h"
#include "PaletteProbe.h"
#include "WeaponProbe.h"
#include "AimTrace.h"

// Forward every export of the real dxgi.dll to dxgi_real.dll.
// deploy.bat places a copy of C:\Windows\System32\dxgi.dll as dxgi_real.dll
// beside the game executable. Generated by tools/gen_proxy_exports.py.
#include "proxy_exports.inc"

namespace {

HMODULE g_self = nullptr;

// Is this the process we are meant to be in? A proxy DLL sitting in a game
// directory can be picked up by launchers, overlays and helper processes. We
// only want to do work inside the game itself.
bool host_is_target() {
    wchar_t exe[MAX_PATH] = {};
    GetModuleFileNameW(nullptr, exe, MAX_PATH);
    std::wstring s = exe;
    for (auto& c : s) c = (wchar_t)towlower(c);
    return s.find(L"grw.exe") != std::wstring::npos;
}

// Wait until the graphics stack is actually present, instead of sleeping a
// fixed five seconds and hoping. Returns true if d3d11 showed up.
bool wait_for_graphics(DWORD timeout_ms) {
    const DWORD step = 50;
    DWORD waited = 0;
    while (waited < timeout_ms) {
        if (GetModuleHandleW(L"d3d11.dll") != nullptr) return true;
        Sleep(step);
        waited += step;
    }
    return false;
}

DWORD WINAPI init_thread(LPVOID) {
    grwxr::log::init(g_self);
    grwxr::crash::install(g_self);

    LOG_INFO("GRW-XR proxy attached. Phase 1: load and log only, no hooks installed.");

    if (!host_is_target()) {
        LOG_WARN("host is not GRW.exe. Standing down, forwarding only.");
        return 0;
    }
    LOG_INFO("host confirmed as GRW.exe");

    // Record which dxgi we are forwarding to, so a mis-deploy is obvious.
    if (HMODULE real = GetModuleHandleW(L"dxgi_real.dll")) {
        wchar_t p[MAX_PATH] = {};
        GetModuleFileNameW(real, p, MAX_PATH);
        char n[MAX_PATH] = {};
        WideCharToMultiByte(CP_UTF8, 0, p, -1, n, sizeof(n), nullptr, nullptr);
        LOG_INFO("forwarding to  : %s", n);
    } else {
        LOG_WARN("dxgi_real.dll not loaded yet (normal: forwards resolve lazily)");
    }

    // Build 26: RENDERDOC CAPTURE MODE, cfg-gated, off by default.
    //
    // This must happen HERE, before anything else touches graphics, because
    // renderdoc.dll has to be loaded before the game creates its D3D11 device
    // in order to hook it. RenderDoc's own injection cannot reach this process
    // at all (Uplay broker + Secure Boot; see docs/RENDERDOC-GUIDE.md 3b), so
    // loading it from inside is the only route left.
    //
    // When it is on, the VR path STANDS DOWN completely: no factory spoof, no
    // Present hook, no OpenXR, no probes. RenderDoc and our proxy would
    // otherwise both be hooking the same swapchain, which is exactly the
    // situation that produces empty or misleading captures. The mod becomes a
    // dxgi forwarder plus a capture key, nothing more.
    if (grwxr::rdoc::enabled()) {
        LOG_INFO("");
        LOG_INFO("=== RENDERDOC CAPTURE MODE (renderdoc_capture=1 in grwxr.cfg) ===");
        LOG_INFO("VR is STOOD DOWN: no factory spoof, no Present hook, no OpenXR.");
        LOG_INFO("Set renderdoc_capture=0 and relaunch to get VR back.");
        if (!grwxr::rdoc::install()) {
            LOG_WARN("rdoc: capture mode requested but unavailable. The game runs "
                     "UNMODIFIED (rule 7). Fix the cfg or set renderdoc_capture=0.");
        }
        for (int tick = 0; ; ++tick) {
            Sleep(1000);
            grwxr::rdoc::poll();
            grwxr::rdoc::drain();
        }
    }

    // Build 15a: the factory stubs may already have fired (the game creates
    // its device the moment dxgi is loaded); report their state and the
    // upsize target now, then drain their events with the other modules.
    grwxr::factory::report_startup();

    // Build 15c: the engine sizes its renderer from the window client size,
    // so the client size the game sees must lie before the renderer reads it.
    grwxr::factory::install_render_size_spoof();

    const bool gfx = wait_for_graphics(30000);
    LOG_INFO("d3d11.dll present: %s", gfx ? "yes" : "NO (timed out after 30s)");

    // Log the loaded graphics modules and where they came from. This is the
    // evidence for Q1 and Q7 that we could not get from outside, because the
    // live process is protected and PowerShell reads zero modules from it.
    const wchar_t* interesting[] = {
        L"dxgi.dll", L"dxgi_real.dll", L"d3d11.dll", L"d3d12.dll",
        L"xinput1_3.dll", L"dinput8.dll", L"EasyAntiCheat_x64.dll",
        L"AnselSDK64.dll", L"openxr_loader.dll", L"steam_api64.dll",
        L"uplay_r1_loader64.dll", L"nvapi64.dll",
    };
    LOG_INFO("--- module survey ---");
    for (const wchar_t* m : interesting) {
        HMODULE h = GetModuleHandleW(m);
        if (!h) {
            char n[64] = {};
            WideCharToMultiByte(CP_UTF8, 0, m, -1, n, sizeof(n), nullptr, nullptr);
            LOG_INFO("  %-24s not loaded", n);
            continue;
        }
        wchar_t p[MAX_PATH] = {};
        GetModuleFileNameW(h, p, MAX_PATH);
        char nm[64] = {}, pn[MAX_PATH] = {};
        WideCharToMultiByte(CP_UTF8, 0, m, -1, nm, sizeof(nm), nullptr, nullptr);
        WideCharToMultiByte(CP_UTF8, 0, p, -1, pn, sizeof(pn), nullptr, nullptr);
        LOG_INFO("  %-24s 0x%p  %s", nm, (void*)h, pn);
    }
    LOG_INFO("--- end module survey ---");

    // Build 46: identify the loaded binary and pick its address table
    // (fail-closed; see GameBuild.h). Logged before any consumer installs so
    // a refusal below always has its reason above it in the log.
    LOG_INFO("");
    grwxr::gamebuild::log_identity();

    // --- PHASE 2: capture the game's D3D11 device via a vtable hook ---------
    LOG_INFO("");
    LOG_INFO("phase 4 step 1: hooking ansel::setConfiguration for the basis vectors");
    grwxr::ansel::install();

    // Phase 4 step 2 (Q9). Read-only: it records the projection parameters and
    // calls the engine's own function unchanged. A signature miss logs loudly
    // and installs nothing, so a failure here cannot break the game.
    LOG_INFO("");
    LOG_INFO("phase 4 step 2: installing the read-only projection probe (Q9)");
    grwxr::camera::install();

    // Build 39: read-only observer on the pooled placement SetTransform,
    // hunting the weapon's handle (user scope call: "the gun rides the
    // controller"). A signature or thunk mismatch logs and installs nothing.
    LOG_INFO("");
    LOG_INFO("build 39: installing the weapon placement observer");
    grwxr::wp::install();

    // Build 50: the aim-reader census. LOG-ONLY, and the route to making the
    // SHOT follow the controller: it records which engine code reads the
    // player's absolute aim angle, and which of those reads happen inside a
    // trigger pull. Installed after the setters (CameraProbe) because it uses
    // their latched player-object pointer as its filter.
    LOG_INFO("");
    LOG_INFO("build 50: installing the aim-reader census (log-only)");
    grwxr::aimtrace::install();

    LOG_INFO("phase 2: installing D3D11 Present hook");
    if (!grwxr::d3d11::install()) {
        LOG_WARN("phase 2 hook NOT installed. Game continues unmodified (rule 7).");
        return 0;
    }
    LOG_INFO("phase 2 hook installed. Waiting for the first Present.");

    // Present deliberately writes no log lines. Drain its findings here, on our
    // own thread, and report liveness periodically without touching the hot path.
    // Heartbeat every second. A 30 second interval told us nothing about WHEN it
    // died; a 1 second heartbeat pins the death to a one second window and tells
    // us the frame count it reached, which distinguishes "died immediately on the
    // first frames" from "ran fine then died at a specific event".
    unsigned long long last = 0;
    for (int tick = 0; ; ++tick) {
        Sleep(1000);
        grwxr::d3d11::drain_capture_log();
        grwxr::vr::drain_log();
        grwxr::vr::drain_input();
        grwxr::vr::poll_config();
        grwxr::xin::poll_install();
        grwxr::xin::drain();
        grwxr::ansel::drain();
        grwxr::camera::drain();
        grwxr::factory::drain();
        grwxr::wp::drain();
        grwxr::aimtrace::drain();

        // Bring OpenXR up once the device exists, on OUR thread, not the render
        // thread. Session creation is slow and allocates; it must not happen
        // inside Present (project rule 8).
        static bool vr_tried = false, vr_armed = false;
        const auto& st = grwxr::d3d11::state();
        if (!vr_tried && st.ready && st.device) {
            vr_tried = true;
            vr_armed = grwxr::vr::init(st);
        } else if (vr_tried && !vr_armed) {
            // Build 38: the headset was not awake when the game launched. Keep
            // watching; the session begins by itself when it wakes, instead of
            // the old behaviour of failing for the whole run.
            vr_armed = grwxr::vr::poll_start();
        }
        if (vr_armed && !grwxr::d3d11::has_present_callback()) {
            grwxr::d3d11::set_present_callback(&grwxr::vr::on_present);
            LOG_INFO("VR mirror armed: the game frame is now going to the headset.");
        }

        // Build 33: the skinning-palette probe (PaletteProbe.h). Installed
        // once the game's immediate context exists; inert until NUMPAD MINUS
        // arms a capture window. All its logging happens in poll(), here.
        static bool pal_tried = false;
        if (!pal_tried && st.ready && st.context) {
            pal_tried = true;
            grwxr::pal::install(st.device, st.context);
        }
        grwxr::pal::poll();

        const unsigned long long now = grwxr::d3d11::frame_count();
        LOG_INFO("hb %4d  frames=%llu  (+%llu in the last second)",
                 tick, now, now - last);
        last = now;
    }
}

}  // namespace

BOOL APIENTRY DllMain(HMODULE module, DWORD reason, LPVOID) {
    switch (reason) {
        case DLL_PROCESS_ATTACH: {
            g_self = module;
            // Cuts thread attach/detach churn; we never use TLS callbacks.
            DisableThreadLibraryCalls(module);
            // Hand off immediately: nothing heavy may run under loader lock.
            if (HANDLE t = CreateThread(nullptr, 0, init_thread, nullptr, 0, nullptr)) {
                CloseHandle(t);
            }
            break;   // the reference implementation is missing this break
        }
        case DLL_PROCESS_DETACH:
            // Distinguishes an orderly shutdown from a hard kill: if this line
            // appears, the process unloaded us properly rather than dying.
            LOG_INFO("DLL_PROCESS_DETACH after %llu frames (orderly unload)",
                     grwxr::d3d11::frame_count());
            grwxr::log::shutdown();
            break;
        default:
            break;
    }
    return TRUE;
}
